# report_generator.py

from datetime import datetime

def generate_report(username, symptoms, diseases):

    report = f"""
------ HealthGenie Medical Report ------

Patient: {username}
Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}

Reported Symptoms:
{symptoms}

Possible Conditions:
{", ".join(diseases) if diseases else "No conditions detected"}

Advice:
Please rest, drink water, and consult a doctor if symptoms continue.

Disclaimer:
This report is generated by AI and should not replace professional medical advice.
"""

    return report